version: "3"
networks:
  backend:
    driver: bridge
services:
  backend-db:
    image: postgres:latest
    container_name: agenda-db
    environment:
      PGDATA: /tmp
      POSTGRES_DB: agenda
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - "./docker/data/db-backend:/var/lib/postgresql/data"
    networks:
      - backend
  backend:
    build: .
    container_name: agenda-backend
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1" # incluir (127.0.0.1 host.docker.internal) em /etc/hosts
    depends_on:
      - backend-db
    networks:
      - backend
